Repository Mysterious-Researchers/bidz, pull requests merged in 2024-06, with the labels that each got.

#22 test: implement integration test
  apps/api/.testing.env
  apps/api/docker-compose.yml
  apps/api/jest-integration.config.json
  apps/api/package.json
  apps/api/src/api/auction/tests/auctions.ispec.ts
  pnpm-lock.yaml
Labels: testing

#21 feature: add Docker configuration for NX monorepo
  apps/api/Dockerfile
  apps/web/Dockerfile
  docker-compose.yml
  package.json
  pnpm-lock.yaml
Labels: feature

#25 ci: added github workflows to the project
  .github/actions/install/action.yml
  .github/workflows/back-actions.yml
  .github/workflows/front-actions.yml
  apps/api/package.json
  apps/api/src/api/auction/auction.service.ispec.ts
  apps/api/src/api/auction/tests/auctions.ispec.ts
  apps/api/src/api/auth/auth.controller.ts
  apps/api/src/api/bid/responses/bids.resposne.ts
  apps/api/src/api/photo/photo.controller.ts
  apps/web/.env
  apps/web/.gitignore
  apps/web/src/app/providers.tsx
  apps/web/src/components/ui/command.tsx
  apps/web/src/components/ui/textarea.tsx
Labels: package

#27 documentation: added tests section
  README.md
Labels: documentation

#28 Link fix
  apps/web/src/app/(application)/_components/auction-list.tsx
Labels: bug
